import { test, expect } from "@playwright/test"

// Copied into a disposable generated project containing examples/product.yaml.
test("resource CRUD, search, filters, pagination and viewer controls", async ({ page, browser }) => {
  await page.goto("/admin/login")
  await page.getByLabel("Email", { exact: true }).fill("browser-admin@example.test")
  await page.getByLabel("Password", { exact: true }).fill("browser test initial password")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  await page.getByRole("link", { name: "Product", exact: true }).click()
  await page.getByRole("button", { name: "Create record" }).click()
  const form = page.getByRole("dialog")
  await form.getByRole("button", { name: "Save record" }).click()
  await expect(form.getByRole("alert").first()).toBeVisible()
  await form.getByLabel("Name", { exact: true }).fill("Browser product")
  await form.getByLabel("Status", { exact: true }).selectOption("enabled")
  await form.getByLabel("Owner ID", { exact: true }).fill("7")
  await form.getByLabel("Price", { exact: true }).fill("12.34")
  await form.getByLabel("Metadata", { exact: true }).fill('{"source":"browser"}')
  await form.getByLabel("Order", { exact: true }).fill("first")
  await form.getByRole("button", { name: "Save record" }).click()
  await expect(form).not.toBeVisible()
  const row = page.getByRole("row").filter({ hasText: "Browser product" })
  await expect(row).toBeVisible()
  await row.getByRole("button", { name: "Edit", exact: true }).click()
  await form.getByLabel("Name", { exact: true }).fill("Browser renamed")
  await form.getByRole("button", { name: "Save record" }).click()
  await expect(form).not.toBeVisible()
  await expect(page.getByRole("cell", { name: "Browser renamed", exact: true })).toBeVisible()

  for (let i = 0; i < 21; i++) {
    const response = await page.request.post("/api/v1/products", { data: { name: `seed-${i}`, status: "enabled", owner_id: i, price: "1.23", order: "batch" } })
    expect(response.status()).toBe(201)
  }
  await page.reload()
  await page.getByRole("button", { name: "Next", exact: true }).click()
  await expect(page.getByText("Page 2 of 2", { exact: true })).toBeVisible()
  await page.getByLabel("Search records").fill("Browser renamed")
  await page.getByRole("button", { name: "Search", exact: true }).click()
  await expect(page.getByText("Page 1 of 1", { exact: true })).toBeVisible()
  await page.getByRole("region", { name: "Table controls" }).getByLabel("Status", { exact: true }).selectOption("disabled")
  await expect(page.getByText("No records match this view.", { exact: true })).toBeVisible()
  await page.getByRole("region", { name: "Table controls" }).getByLabel("Status", { exact: true }).selectOption("enabled")
  const renamed = page.getByRole("row").filter({ hasText: "Browser renamed" })
  await expect(renamed).toBeVisible()
  await renamed.getByRole("button", { name: "Delete", exact: true }).click()
  await page.getByRole("dialog").getByRole("button", { name: "Delete", exact: true }).click()
  await expect(page.getByRole("dialog")).not.toBeVisible()
  await expect(page.getByText("No records match this view.", { exact: true })).toBeVisible()

  const created = await page.request.post("/auth/users", { data: { email: "resource-viewer@example.test", password: "resource viewer password", role: "viewer" } })
  expect(created.status()).toBe(201)
  const context = await browser.newContext({ baseURL: new URL(page.url()).origin })
  try {
    const viewer = await context.newPage()
    await viewer.goto("/admin/login")
    await viewer.getByLabel("Email", { exact: true }).fill("resource-viewer@example.test")
    await viewer.getByLabel("Password", { exact: true }).fill("resource viewer password")
    await viewer.getByRole("button", { name: "Sign in", exact: true }).click()
    await viewer.getByRole("link", { name: "Product", exact: true }).click()
    await viewer.getByLabel("Search records").fill("seed-0")
    await viewer.getByRole("button", { name: "Search", exact: true }).click()
    await expect(viewer.getByRole("cell", { name: "seed-0", exact: true })).toBeVisible()
    await expect(viewer.getByRole("button", { name: "Create record" })).toHaveCount(0)
    await expect(viewer.getByRole("button", { name: "Edit", exact: true })).toHaveCount(0)
    expect((await context.request.post("/api/v1/products", { data: { name: "forbidden", status: "enabled" } })).status()).toBe(403)
  } finally { await context.close() }
})
