// Package generate creates and updates go-backend-kit projects.
package generate

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/alphayan/go-backend-kit/internal/spec"
	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
)

const generatedMarker = "Code generated by gobackend; DO NOT EDIT."
const gormGeneratedMarker = "Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT."

//go:embed all:scaffold
var scaffoldFS embed.FS

type Generator struct {
	Version            string
	DevelopmentReplace string
}

type projectData struct {
	Module             string
	Version            string
	DevelopmentReplace string
}

func (g Generator) New(ctx context.Context, target, modulePath string) error {
	if err := module.CheckPath(modulePath); err != nil {
		return fmt.Errorf("invalid module path: %w", err)
	}
	if g.Version == "" {
		g.Version = "v0.1.0"
	}
	abs, err := filepath.Abs(target)
	if err != nil {
		return err
	}
	currentTarget := false
	if current, err := os.Getwd(); err == nil {
		currentInfo, currentErr := os.Stat(current)
		targetInfo, targetErr := os.Stat(abs)
		if currentErr == nil && targetErr == nil && os.SameFile(currentInfo, targetInfo) {
			currentTarget = true
		}
	}
	if err := ensureMissingOrEmpty(abs); err != nil {
		return err
	}
	parent := filepath.Dir(abs)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return err
	}
	stage, err := os.MkdirTemp(parent, ".gobackend-new-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(stage)

	if err := renderScaffold(ctx, stage, projectData{Module: modulePath, Version: g.Version, DevelopmentReplace: filepath.ToSlash(g.DevelopmentReplace)}); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(stage, "resources"), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(stage, "resources", ".gitkeep"), nil, 0o644); err != nil {
		return err
	}
	if err := g.Generate(ctx, stage); err != nil {
		return err
	}
	if err := tidyModule(ctx, stage); err != nil {
		return err
	}
	if currentTarget {
		return installIntoEmptyDirectory(stage, abs)
	}
	if info, err := os.Stat(abs); err == nil && info.IsDir() {
		if err := os.Remove(abs); err != nil {
			return err
		}
	}
	if err := os.Rename(stage, abs); err != nil {
		return fmt.Errorf("install project atomically: %w", err)
	}
	return nil
}

func (g Generator) Add(ctx context.Context, root, source string) error {
	data, err := os.ReadFile(source)
	if err != nil {
		return fmt.Errorf("read resource: %w", err)
	}
	resource, err := spec.Parse(data)
	if err != nil {
		return err
	}
	resourcesDir := filepath.Join(root, "resources")
	if err := os.MkdirAll(resourcesDir, 0o755); err != nil {
		return err
	}
	destination := filepath.Join(resourcesDir, resource.Package+".yaml")
	if _, err := os.Stat(destination); err == nil {
		return fmt.Errorf("resource %q already exists", resource.Name)
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.WriteFile(destination, data, 0o644); err != nil {
		return fmt.Errorf("copy resource: %w", err)
	}
	if err := g.Generate(ctx, root); err != nil {
		_ = os.Remove(destination)
		return err
	}
	return nil
}

func (g Generator) Generate(ctx context.Context, root string) error {
	modulePath, err := readModule(root)
	if err != nil {
		return err
	}
	resources, err := loadResources(filepath.Join(root, "resources"))
	if err != nil {
		return err
	}
	desired, err := renderDesired(ctx, root, modulePath, resources)
	if err != nil {
		return err
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if err := installGenerated(root, desired); err != nil {
		return err
	}
	if err := ensureExtensions(root, resources); err != nil {
		return err
	}
	return nil
}

func (g Generator) Check(ctx context.Context, root string) error {
	modulePath, err := readModule(root)
	if err != nil {
		return err
	}
	resources, err := loadResources(filepath.Join(root, "resources"))
	if err != nil {
		return err
	}
	desired, err := renderDesired(ctx, root, modulePath, resources)
	if err != nil {
		return err
	}
	var drift []string
	for name, want := range desired {
		if err := ctx.Err(); err != nil {
			return err
		}
		got, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
		if err != nil || !bytes.Equal(got, want) {
			drift = append(drift, name)
		}
	}
	stale, err := staleGenerated(root, desired)
	if err != nil {
		return err
	}
	drift = append(drift, stale...)
	sort.Strings(drift)
	if len(drift) > 0 {
		return fmt.Errorf("generated files are out of date: %s; run go tool gobackend generate", strings.Join(drift, ", "))
	}
	return nil
}

func renderDesired(ctx context.Context, root, modulePath string, resources []spec.Resource) (map[string][]byte, error) {
	desired, err := renderGenerated(modulePath, resources)
	if err != nil {
		return nil, err
	}
	if len(resources) == 0 {
		return desired, nil
	}
	stage, err := os.MkdirTemp(root, ".gobackend-gorm-*")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(stage)
	for _, resource := range resources {
		modelName := "internal/resources/" + resource.Package + "/model_gen.go"
		model, ok := desired[modelName]
		if !ok {
			return nil, fmt.Errorf("missing generated model for %s", resource.Name)
		}
		input := filepath.Join(stage, resource.Package, "model_gen.go")
		output := filepath.Join(stage, resource.Package, "gormgen")
		if err := os.MkdirAll(filepath.Dir(input), 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(input, model, 0o644); err != nil {
			return nil, err
		}
		command := exec.CommandContext(ctx, "go", "tool", "gorm", "gen", "-i", input, "-o", output)
		command.Dir = root
		command.Env = goReadonlyEnvironment()
		if result, err := command.CombinedOutput(); err != nil {
			return nil, fmt.Errorf("generate GORM field helpers for %s: %w: %s", resource.Name, err, strings.TrimSpace(string(result)))
		}
		generated, err := os.ReadFile(filepath.Join(output, "model_gen.go"))
		if err != nil {
			return nil, fmt.Errorf("read GORM field helpers for %s: %w", resource.Name, err)
		}
		desired["internal/resources/"+resource.Package+"/gormgen/query_gen.go"] = generated
	}
	return desired, nil
}

func tidyModule(ctx context.Context, root string) error {
	command := exec.CommandContext(ctx, "go", "mod", "tidy")
	command.Dir = root
	if output, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("resolve generated project modules: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func goReadonlyEnvironment() []string {
	environment := os.Environ()
	for i := len(environment) - 1; i >= 0; i-- {
		if strings.HasPrefix(environment[i], "GOFLAGS=") {
			environment = append(environment[:i], environment[i+1:]...)
		}
	}
	return append(environment, "GOFLAGS=-mod=readonly")
}

func installIntoEmptyDirectory(stage, target string) error {
	entries, err := os.ReadDir(stage)
	if err != nil {
		return err
	}
	moved := make([]string, 0, len(entries))
	for _, entry := range entries {
		name := entry.Name()
		if err := os.Rename(filepath.Join(stage, name), filepath.Join(target, name)); err != nil {
			for i := len(moved) - 1; i >= 0; i-- {
				_ = os.Rename(filepath.Join(target, moved[i]), filepath.Join(stage, moved[i]))
			}
			return fmt.Errorf("install project into current directory: %w", err)
		}
		moved = append(moved, name)
	}
	return nil
}

func ensureMissingOrEmpty(path string) error {
	entries, err := os.ReadDir(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if len(entries) != 0 {
		return fmt.Errorf("target directory %q is not empty", path)
	}
	return nil
}

func renderScaffold(ctx context.Context, root string, data projectData) error {
	return fs.WalkDir(scaffoldFS, "scaffold", func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if err := ctx.Err(); err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		rel := strings.TrimPrefix(path, "scaffold/")
		rel = strings.TrimSuffix(rel, ".tmpl")
		content, err := fs.ReadFile(scaffoldFS, path)
		if err != nil {
			return err
		}
		tmpl, err := template.New(rel).Option("missingkey=error").Parse(string(content))
		if err != nil {
			return fmt.Errorf("parse scaffold %s: %w", rel, err)
		}
		var rendered bytes.Buffer
		if err := tmpl.Execute(&rendered, data); err != nil {
			return fmt.Errorf("render scaffold %s: %w", rel, err)
		}
		output := rendered.Bytes()
		if strings.HasSuffix(rel, ".go") {
			output, err = format.Source(output)
			if err != nil {
				return fmt.Errorf("format scaffold %s: %w", rel, err)
			}
		}
		destination := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return err
		}
		mode := fs.FileMode(0o644)
		if strings.HasSuffix(rel, ".sh") {
			mode = 0o755
		}
		return os.WriteFile(destination, output, mode)
	})
}

func readModule(root string) (string, error) {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return "", fmt.Errorf("read go.mod: %w", err)
	}
	parsed, err := modfile.Parse("go.mod", data, nil)
	if err != nil {
		return "", fmt.Errorf("parse go.mod: %w", err)
	}
	if parsed.Module == nil {
		return "", errors.New("go.mod has no module directive")
	}
	return parsed.Module.Mod.Path, nil
}

func loadResources(dir string) ([]spec.Resource, error) {
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var resources []spec.Resource
	seenNames, seenPackages := map[string]struct{}{}, map[string]struct{}{}
	seenTables, seenRoutes := map[string]struct{}{}, map[string]struct{}{}
	for _, entry := range entries {
		if entry.IsDir() || (filepath.Ext(entry.Name()) != ".yaml" && filepath.Ext(entry.Name()) != ".yml") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			return nil, err
		}
		resource, err := spec.Parse(data)
		if err != nil {
			return nil, fmt.Errorf("resources/%s: %w", entry.Name(), err)
		}
		if _, exists := seenNames[resource.Name]; exists {
			return nil, fmt.Errorf("duplicate resource name %q", resource.Name)
		}
		if _, exists := seenPackages[resource.Package]; exists {
			return nil, fmt.Errorf("resource %q collides with generated package %q", resource.Name, resource.Package)
		}
		if _, exists := seenTables[resource.Table]; exists {
			return nil, fmt.Errorf("duplicate resource table %q", resource.Table)
		}
		if _, exists := seenRoutes[resource.Route]; exists {
			return nil, fmt.Errorf("duplicate resource route %q", resource.Route)
		}
		seenNames[resource.Name], seenPackages[resource.Package] = struct{}{}, struct{}{}
		seenTables[resource.Table], seenRoutes[resource.Route] = struct{}{}, struct{}{}
		resources = append(resources, resource)
	}
	sort.Slice(resources, func(i, j int) bool { return resources[i].Name < resources[j].Name })
	return resources, nil
}

func installGenerated(root string, desired map[string][]byte) error {
	for name := range desired {
		target := filepath.Join(root, filepath.FromSlash(name))
		data, err := os.ReadFile(target)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return err
		}
		if !isManagedGenerated(name, data) {
			return fmt.Errorf("refusing to overwrite unowned file %s", name)
		}
	}
	stage, err := os.MkdirTemp(root, ".gobackend-generate-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(stage)
	names := make([]string, 0, len(desired))
	for name, data := range desired {
		names = append(names, name)
		target := filepath.Join(stage, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(target, data, 0o644); err != nil {
			return err
		}
	}
	sort.Strings(names)
	stale, err := staleGenerated(root, desired)
	if err != nil {
		return err
	}
	for _, name := range names {
		target := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		if err := replaceFile(filepath.Join(stage, filepath.FromSlash(name)), target); err != nil {
			return fmt.Errorf("replace %s: %w", name, err)
		}
	}
	for _, name := range stale {
		if err := os.Remove(filepath.Join(root, filepath.FromSlash(name))); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
	}
	return nil
}

func staleGenerated(root string, desired map[string][]byte) ([]string, error) {
	var stale []string
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			if strings.HasPrefix(entry.Name(), ".gobackend-") || entry.Name() == ".git" {
				return filepath.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if _, ok := desired[rel]; ok {
			return nil
		}
		managedName := strings.HasSuffix(rel, "_gen.go") || strings.HasSuffix(rel, "_gen_test.go") || rel == "openapi/openapi_gen.json"
		if !managedName {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if isManagedGenerated(rel, data) {
			stale = append(stale, rel)
		}
		return nil
	})
	sort.Strings(stale)
	return stale, err
}

func isManagedGenerated(name string, data []byte) bool {
	if name == "openapi/openapi_gen.json" {
		return bytes.Contains(data, []byte(`"x-generated-by": "gobackend"`))
	}
	return bytes.Contains(data, []byte(generatedMarker)) || bytes.Contains(data, []byte(gormGeneratedMarker))
}

func ensureExtensions(root string, resources []spec.Resource) error {
	for _, resource := range resources {
		path := filepath.Join(root, "internal", "resources", resource.Package, "custom.go")
		if _, err := os.Stat(path); err == nil {
			continue
		} else if !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		content := fmt.Sprintf("// Package %s contains handwritten extensions for %s.\npackage %s\n", resource.Package, resource.Name, resource.Package)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func marshalJSON(value any) ([]byte, error) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}
