package generate_test

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/alphayan/go-backend-kit/internal/generate"
)

const taskYAML = `schema_version: 1
name: Task
table: tasks
route: /tasks
fields:
  - name: title
    type: string
    required: true
    max_length: 200
    searchable: true
  - name: done
    type: bool
    filterable: true
    sortable: true
  - name: note
    type: text
    nullable: true
`

const allTypesYAML = `schema_version: 1
name: AllTypes
table: all_types
route: /all-types
fields:
  - {name: short_text, type: string}
  - {name: long_text, type: text}
  - {name: active, type: bool}
  - {name: small_count, type: int32, min: 0, max: 100}
  - {name: large_count, type: int64}
  - {name: ratio, type: float64}
  - {name: amount, type: decimal, min: 0}
  - {name: happened_at, type: time}
  - {name: external_id, type: uuid}
  - {name: metadata, type: json}
`

const constrainedYAML = `schema_version: 1
name: Tiny
table: tiny
route: /tiny
fields:
  - {name: code, type: string, required: true, max_length: 1, searchable: true}
  - {name: count, type: int32, required: true, min: 1, max: 2, filterable: true, sortable: true}
`

func TestNewAddGenerateAndCheck(t *testing.T) {
	ctx := context.Background()
	root := filepath.Join(t.TempDir(), "task-api")
	g := testGenerator(t)
	if err := g.New(ctx, root, "example.com/task-api"); err != nil {
		t.Fatalf("New() error = %v", err)
	}
	source := filepath.Join(t.TempDir(), "task.yaml")
	rich := strings.Replace(taskYAML, "max_length: 200", "max_length: 200\n    unique: true", 1)
	if err := os.WriteFile(source, []byte(rich), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := g.Add(ctx, root, source); err != nil {
		t.Fatalf("Add() error = %v", err)
	}
	if err := g.Check(ctx, root); err != nil {
		t.Fatalf("Check() error = %v", err)
	}

	wantFiles := []string{
		".env.example",
		".gitignore",
		".github/workflows/ci.yml",
		"cmd/api/main.go",
		"internal/platform/config/config_test.go",
		"internal/platform/database/database_test.go",
		"migrations/.gitkeep",
		"internal/resources/task/model_gen.go",
		"internal/resources/task/dto_gen.go",
		"internal/resources/task/gormgen/query_gen.go",
		"internal/resources/task/store_gen.go",
		"internal/resources/task/http_gen.go",
		"internal/resources/task/contract_gen_test.go",
		"internal/generated/register_gen.go",
		"openapi/openapi_gen.json",
		"tools/gormschema/main_gen.go",
	}
	for _, name := range wantFiles {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(name))); err != nil {
			t.Errorf("generated file %s: %v", name, err)
		}
	}
	obsoleteFiles := []string{
		"internal/resources/task/repository_gen.go",
		"internal/resources/task/service_gen.go",
		"internal/resources/task/handler_gen.go",
		"internal/resources/task/routes_gen.go",
		"internal/resources/task/custom.go",
		"internal/platform/repository/repository.go",
	}
	for _, name := range obsoleteFiles {
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(name))); !errors.Is(err, os.ErrNotExist) {
			t.Errorf("obsolete generated file %s still exists: %v", name, err)
		}
	}
	helper, err := os.ReadFile(filepath.Join(root, "internal", "resources", "task", "gormgen", "query_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(helper), "Code generated by 'gorm.io/cli/gorm'") {
		t.Fatal("field helpers were not produced by the official GORM CLI")
	}
	storeData, err := os.ReadFile(filepath.Join(root, "internal/resources/task/store_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	storeSource := string(storeData)
	for _, required := range []string{
		"type store struct",
		"clause.Eq{",
		"Column: gormgen.Task.Done.Column()",
		"Value:",
		"gormgen.Task.Done.Asc()",
		"func (s store) create(",
		"func (s store) update(",
		"func translateDatabaseError(",
	} {
		if !strings.Contains(storeSource, required) {
			t.Errorf("generated store missing %q", required)
		}
	}

	dtoData, err := os.ReadFile(filepath.Join(root, "internal/resources/task/dto_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	for _, required := range []string{
		"func createValues(input CreateTaskInput)",
		"func updateValues(input UpdateTaskInput)",
	} {
		if !strings.Contains(string(dtoData), required) {
			t.Errorf("generated DTO helpers missing %q", required)
		}
	}

	httpData, err := os.ReadFile(filepath.Join(root, "internal/resources/task/http_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	httpSource := string(httpData)
	for _, required := range []string{
		"type handler struct",
		"h := handler{store: store{db: db}}",
		"func Register(group *echo.Group, db *gorm.DB)",
	} {
		if !strings.Contains(httpSource, required) {
			t.Errorf("generated HTTP resource missing %q", required)
		}
	}

	combined := storeSource + "\n" + httpSource
	for _, forbidden := range []string{
		"type Repository interface",
		"type Service interface",
		"Base[",
		"NewHandler(",
		"NewService(",
		"NewRepository(",
	} {
		if strings.Contains(combined, forbidden) {
			t.Errorf("generated resource retains speculative abstraction %q", forbidden)
		}
	}
	ci, err := os.ReadFile(filepath.Join(root, ".github", "workflows", "ci.yml"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(ci), "schema diff --env ci --from env://url --to env://src --exclude atlas_schema_revisions --format '{{ sql . \"  \" }}'") {
		t.Fatal("generated CI does not check migration/schema drift")
	}
	moduleFile, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(moduleFile), "go 1.26.4\n\ntoolchain go1.26.5\n") {
		t.Fatal("generated go.mod does not separate the Go minimum from the preferred toolchain")
	}
	if strings.Contains(string(ci), "migrate lint") {
		t.Fatal("generated CI promises Atlas linting that Community edition does not provide")
	}
	if !strings.Contains(string(ci), "migrate apply --env ci") ||
		!strings.Contains(string(ci), "schema diff --env ci --from env://url --to env://src") {
		t.Fatal("generated CI does not apply and compare versioned migrations")
	}
	makefile, err := os.ReadFile(filepath.Join(root, "Makefile"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(makefile), "migrate-lint") {
		t.Fatal("generated Makefile exposes unsupported Atlas Community linting")
	}

	handwritten := filepath.Join(root, "internal/resources/task/rules.go")
	const handwrittenSource = "package task\n\nconst HandwrittenRule = true\n"
	if err := os.WriteFile(handwritten, []byte(handwrittenSource), 0o644); err != nil {
		t.Fatal(err)
	}
	before := snapshot(t, root)
	if err := g.Generate(ctx, root); err != nil {
		t.Fatalf("second Generate() error = %v", err)
	}
	after := snapshot(t, root)
	if before != after {
		t.Fatal("second generation changed the project")
	}
	data, err := os.ReadFile(handwritten)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != handwrittenSource {
		t.Fatalf("generation changed handwritten source: %q", data)
	}
	if err := os.WriteFile(filepath.Join(root, "internal", "resources", "task", "gormgen", "query_gen.go"), append(helper, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := g.Check(ctx, root); err == nil || !strings.Contains(err.Error(), "gormgen/query_gen.go") {
		t.Fatalf("Check() did not report GORM CLI helper drift: %v", err)
	}
}

func TestCheckDetectsDrift(t *testing.T) {
	ctx := context.Background()
	root := filepath.Join(t.TempDir(), "api")
	g := testGenerator(t)
	if err := g.New(ctx, root, "example.com/api"); err != nil {
		t.Fatal(err)
	}
	generated := filepath.Join(root, "internal/generated/register_gen.go")
	if err := os.WriteFile(generated, []byte("package generated\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := g.Check(ctx, root); err == nil {
		t.Fatal("Check() error = nil, want drift error")
	}
}

func TestGeneratePreservesUnownedGeneratedFiles(t *testing.T) {
	root := filepath.Join(t.TempDir(), "api")
	g := testGenerator(t)
	if err := g.New(t.Context(), root, "example.com/api"); err != nil {
		t.Fatal(err)
	}

	const content = "// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.\n\npackage generated\n"
	paths := []string{
		"internal/custom/query_gen.go",
		"internal/resources/custom/gormgen/query_gen.go",
		".worktrees/other/internal/resources/task/gormgen/query_gen.go",
	}
	for _, name := range paths {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	if err := g.Generate(t.Context(), root); err != nil {
		t.Fatal(err)
	}
	for _, name := range paths {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(name)))
		if err != nil {
			t.Errorf("unowned generated file %s was removed: %v", name, err)
			continue
		}
		if string(data) != content {
			t.Errorf("unowned generated file %s changed", name)
		}
	}
}

func TestNewWritesGeneratedManifest(t *testing.T) {
	root := filepath.Join(t.TempDir(), "api")
	g := testGenerator(t)
	if err := g.New(t.Context(), root, "example.com/api"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(root, ".gobackend-generated.json"))
	if err != nil {
		t.Fatal(err)
	}
	for _, value := range []string{
		`"generated_by": "gobackend"`,
		`"version": 1`,
		`"internal/generated/register_gen.go"`,
	} {
		if !strings.Contains(string(data), value) {
			t.Errorf("manifest does not contain %q:\n%s", value, data)
		}
	}
}

func TestGenerateRemovesManifestOwnedUnchangedStaleFiles(t *testing.T) {
	root, g := generatedTaskProject(t)
	if err := os.Remove(filepath.Join(root, "resources", "task.yaml")); err != nil {
		t.Fatal(err)
	}
	stale := filepath.Join(root, "internal", "resources", "task", "model_gen.go")
	if err := g.Generate(t.Context(), root); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(stale); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("unchanged manifest-owned stale file still exists: %v", err)
	}
}

func TestGeneratePreservesModifiedManifestOwnedStaleFiles(t *testing.T) {
	root, g := generatedTaskProject(t)
	if err := os.Remove(filepath.Join(root, "resources", "task.yaml")); err != nil {
		t.Fatal(err)
	}
	stale := filepath.Join(root, "internal", "resources", "task", "model_gen.go")
	data, err := os.ReadFile(stale)
	if err != nil {
		t.Fatal(err)
	}
	data = append(data, []byte("\n// local investigation\n")...)
	if err := os.WriteFile(stale, data, 0o644); err != nil {
		t.Fatal(err)
	}

	err = g.Generate(t.Context(), root)
	if err == nil || !strings.Contains(err.Error(), "modified stale generated file") {
		t.Fatalf("Generate() error = %v, want modified stale generated file", err)
	}
	got, readErr := os.ReadFile(stale)
	if readErr != nil {
		t.Fatalf("modified stale file was removed: %v", readErr)
	}
	if string(got) != string(data) {
		t.Fatal("modified stale file changed")
	}
}

func TestGenerateNeverOverwritesUnownedManagedPath(t *testing.T) {
	root := filepath.Join(t.TempDir(), "api")
	g := testGenerator(t)
	if err := g.New(context.Background(), root, "example.com/api"); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, "internal", "generated", "register_gen.go")
	if err := os.WriteFile(path, []byte("package generated\n\nconst Handwritten = true\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	before := snapshot(t, root)
	if err := g.Generate(context.Background(), root); err == nil || !strings.Contains(err.Error(), "unowned") {
		t.Fatalf("Generate() error = %v", err)
	}
	if after := snapshot(t, root); after != before {
		t.Fatal("failed generation partially changed the project")
	}
}

func TestGeneratedContractCoversCRUDAndSafety(t *testing.T) {
	ctx := context.Background()
	root := filepath.Join(t.TempDir(), "api")
	g := testGenerator(t)
	if err := g.New(ctx, root, "example.com/api"); err != nil {
		t.Fatal(err)
	}
	source := filepath.Join(t.TempDir(), "task.yaml")
	rich := strings.Replace(taskYAML, "max_length: 200", "max_length: 200\n    unique: true", 1)
	if err := os.WriteFile(source, []byte(rich), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := g.Add(ctx, root, source); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(root, "internal/resources/task/contract_gen_test.go"))
	if err != nil {
		t.Fatal(err)
	}
	for _, required := range []string{"Create", "List", "Get", "Update", "Delete", "zero-value PATCH", "explicit null", "unique conflict", "base field injection", "internal error redaction"} {
		if !strings.Contains(string(data), required) {
			t.Errorf("generated contract does not cover %q", required)
		}
	}
}

func TestNewRejectsNonEmptyDirectory(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "keep.txt"), []byte("mine"), 0o600); err != nil {
		t.Fatal(err)
	}
	err := (generate.Generator{}).New(context.Background(), root, "example.com/api")
	if err == nil {
		t.Fatal("New() error = nil")
	}
}

func TestNewSupportsEmptyCurrentWorkingDirectory(t *testing.T) {
	g := testGenerator(t)
	original, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	target := t.TempDir()
	if err := os.Chdir(target); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(original) })
	before, err := os.Stat(".")
	if err != nil {
		t.Fatal(err)
	}
	if err := g.New(context.Background(), ".", "example.com/api"); err != nil {
		t.Fatalf("New() error = %v", err)
	}
	after, err := os.Stat(".")
	if err != nil {
		t.Fatal(err)
	}
	if !os.SameFile(before, after) {
		t.Fatal("New() replaced the current working directory inode")
	}
	if _, err := os.Stat("go.mod"); err != nil {
		t.Fatalf("generated go.mod: %v", err)
	}
}

func TestGenerateRejectsPackageCollisions(t *testing.T) {
	root := filepath.Join(t.TempDir(), "api")
	g := testGenerator(t)
	if err := g.New(context.Background(), root, "example.com/api"); err != nil {
		t.Fatal(err)
	}
	resources := map[string]string{
		"one.yaml": "schema_version: 1\nname: APIKey\ntable: api_keys\nroute: /api-keys\nfields: []\n",
		"two.yaml": "schema_version: 1\nname: Apikey\ntable: other_keys\nroute: /other-keys\nfields: []\n",
	}
	for name, content := range resources {
		if err := os.WriteFile(filepath.Join(root, "resources", name), []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	if err := g.Generate(context.Background(), root); err == nil {
		t.Fatal("Generate() error = nil, want package collision")
	}
}

func TestGeneratedProjectCompilesAndRunsContract(t *testing.T) {
	ctx := context.Background()
	root := filepath.Join(t.TempDir(), "task-api")
	kitRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	g := generate.Generator{Version: "v0.1.0", DevelopmentReplace: kitRoot}
	if err := g.New(ctx, root, "example.com/task-api"); err != nil {
		t.Fatal(err)
	}
	source := filepath.Join(t.TempDir(), "task.yaml")
	rich := strings.Replace(taskYAML, "max_length: 200", "max_length: 200\n    unique: true", 1)
	if err := os.WriteFile(source, []byte(rich), 0o600); err != nil {
		t.Fatal(err)
	}
	run(t, root, "go", "tool", "gobackend", "add", source)
	run(t, root, "go", "mod", "tidy", "-diff")
	allTypes := filepath.Join(t.TempDir(), "all_types.yaml")
	if err := os.WriteFile(allTypes, []byte(allTypesYAML), 0o600); err != nil {
		t.Fatal(err)
	}
	run(t, root, "go", "tool", "gobackend", "add", allTypes)
	baseOnly := filepath.Join(t.TempDir(), "base_only.yaml")
	if err := os.WriteFile(baseOnly, []byte("schema_version: 1\nname: BaseOnly\ntable: base_only\nroute: /base-only\nfields: []\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	run(t, root, "go", "tool", "gobackend", "add", baseOnly)
	run(t, root, "go", "tool", "gobackend", "add", filepath.Join(kitRoot, "examples", "defaults.yaml"))
	constrained := filepath.Join(t.TempDir(), "tiny.yaml")
	if err := os.WriteFile(constrained, []byte(constrainedYAML), 0o600); err != nil {
		t.Fatal(err)
	}
	run(t, root, "go", "tool", "gobackend", "add", constrained)
	run(t, root, "go", "tool", "gobackend", "generate")
	run(t, root, "go", "tool", "gobackend", "check")
	run(t, root, "go", "tool", "gorm", "--help")
	run(t, root, "go", "test", "./...")
}

func run(t *testing.T, dir, name string, args ...string) {
	t.Helper()
	command := exec.Command(name, args...)
	command.Dir = dir
	output, err := command.CombinedOutput()
	if err != nil {
		t.Fatalf("%s %s: %v\n%s", name, strings.Join(args, " "), err, output)
	}
}

func testGenerator(t *testing.T) generate.Generator {
	t.Helper()
	kitRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return generate.Generator{Version: "v0.1.0", DevelopmentReplace: kitRoot}
}

func generatedTaskProject(t *testing.T) (string, generate.Generator) {
	t.Helper()
	root := filepath.Join(t.TempDir(), "api")
	g := testGenerator(t)
	if err := g.New(t.Context(), root, "example.com/api"); err != nil {
		t.Fatal(err)
	}
	source := filepath.Join(t.TempDir(), "task.yaml")
	if err := os.WriteFile(source, []byte(taskYAML), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := g.Add(t.Context(), root, source); err != nil {
		t.Fatal(err)
	}
	return root, g
}

func snapshot(t *testing.T, root string) string {
	t.Helper()
	var out strings.Builder
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || strings.Contains(path, string(filepath.Separator)+".git"+string(filepath.Separator)) {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		out.WriteString(filepath.ToSlash(rel))
		out.WriteByte(0)
		out.Write(data)
		out.WriteByte(0)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out.String()
}
