package generate

const httpTemplateFiber = `// Code generated by gobackend; DO NOT EDIT.

package {{.Resource.Package}}

import (
	"bytes"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"{{.Module}}/internal/platform/apperror"
	"{{.Module}}/internal/platform/httpx"
	"github.com/gofiber/fiber/v3"
	"gorm.io/gorm"
)

type handler struct { store store }

func Register(router fiber.Router, db *gorm.DB) {
	h := handler{store: store{db: db}}
	resource := router.Group({{quote .Resource.Route}})
	resource.Get("", h.list)
	resource.Get("/:id", h.get)
	resource.Post("", h.create)
	resource.Patch("/:id", h.update)
	resource.Delete("/:id", h.delete)
}

func (h handler) list(c fiber.Ctx) error {
	page, pageSize, err := httpx.ParsePage(c.Query("page"), c.Query("page_size"))
	if err != nil { return httpx.WriteError(c, err) }
	sortValue := c.Query("sort")
	switch strings.TrimPrefix(sortValue, "-") {
	case "", "id", "created_at"{{range sortableFields .Resource}}, {{quote .Name}}{{end}}:
	default: return httpx.WriteError(c, apperror.BadRequest("invalid_sort", "sort is not allowed"))
	}
	{{if filterFields .Resource}}query{{else}}_{{end}}, parseErr := url.ParseQuery(string(c.Request().URI().QueryString()))
	if parseErr != nil { return httpx.WriteError(c, apperror.BadRequest("invalid_filter", "query string is invalid")) }
	exact := map[string]any{}
{{range filterFields .Resource}}	if values, present := query[{{quote .Name}}]; present { if len(values) != 1 { return httpx.WriteError(c, apperror.BadRequest("invalid_filter", {{quote (printf "%s filter must be provided once" .Name)}})) }; value, parseErr := httpx.ParseScalar(values[0], {{quote (printf "%s" .Type)}}); if parseErr != nil { return httpx.WriteError(c, apperror.BadRequest("invalid_filter", {{quote (printf "invalid %s filter" .Name)}})) }; exact[{{quote .Name}}] = value }
{{end}}	items, total, err := h.store.list(c.Context(), filters{page: page, pageSize: pageSize, sort: sortValue, query: c.Query("q"), exact: exact})
	if err != nil { return httpx.WriteError(c, apperror.FromDatabase(err)) }
	return httpx.WriteData(c, http.StatusOK, httpx.NewPage(items, page, pageSize, total))
}

func (h handler) get(c fiber.Ctx) error {
	id, err := parseID(c.Params("id")); if err != nil { return httpx.WriteError(c, err) }
	item, err := h.store.get(c.Context(), id)
	if err != nil { return httpx.WriteError(c, apperror.FromDatabase(err)) }
	return httpx.WriteData(c, http.StatusOK, item)
}

func (h handler) create(c fiber.Ctx) error {
	var input Create{{.Resource.Name}}Input
	if err := httpx.DecodeJSON(bytes.NewReader(c.Body()), &input); err != nil { return httpx.WriteError(c, apperror.BadRequest("invalid_json", "request body must be valid JSON")) }
	values, details := createValues(input)
	if len(details) > 0 { return httpx.WriteError(c, apperror.Validation(details)) }
	item, err := h.store.create(c.Context(), values)
	if err != nil { return httpx.WriteError(c, apperror.FromDatabase(err)) }
	return httpx.WriteData(c, http.StatusCreated, item)
}

func (h handler) update(c fiber.Ctx) error {
	id, err := parseID(c.Params("id")); if err != nil { return httpx.WriteError(c, err) }
	var input Update{{.Resource.Name}}Input
	if err := httpx.DecodeJSON(bytes.NewReader(c.Body()), &input); err != nil { return httpx.WriteError(c, apperror.BadRequest("invalid_json", "request body must be valid JSON")) }
	values, details := updateValues(input)
	if len(details) > 0 { return httpx.WriteError(c, apperror.Validation(details)) }
	if len(values) == 0 { return httpx.WriteError(c, apperror.BadRequest("empty_update", "at least one field must be provided")) }
	item, err := h.store.update(c.Context(), id, values)
	if err != nil { return httpx.WriteError(c, apperror.FromDatabase(err)) }
	return httpx.WriteData(c, http.StatusOK, item)
}

func (h handler) delete(c fiber.Ctx) error {
	id, err := parseID(c.Params("id")); if err != nil { return httpx.WriteError(c, err) }
	if err := h.store.delete(c.Context(), id); err != nil { return httpx.WriteError(c, apperror.FromDatabase(err)) }
	return c.SendStatus(http.StatusNoContent)
}

func parseID(raw string) (int64, error) {
	id, err := strconv.ParseInt(raw, 10, 64)
	if err != nil || id <= 0 { return 0, apperror.BadRequest("invalid_id", "id must be a positive integer") }
	return id, nil
}
`

const contractTemplateFiber = `// Code generated by gobackend; DO NOT EDIT.

package {{.Resource.Package}}

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
{{if .Options.IsPostgres}}	"os"
{{end}}{{if hasDefaults .Resource}}	"reflect"
{{end}}	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/libtnb/sqlite"
{{if .Options.IsPostgres}}	"gorm.io/driver/postgres"
{{end}}	"gorm.io/gorm"
	gormlogger "gorm.io/gorm/logger"
)

func TestGenerated{{.Resource.Name}}CRUDContract(t *testing.T) {
	config := &gorm.Config{TranslateError: true, NowFunc: func() time.Time { return time.Now().UTC() }, Logger: gormlogger.Default.LogMode(gormlogger.Silent)}
	var db *gorm.DB
	var err error
{{if .Options.IsPostgres}}	if dsn := os.Getenv("TEST_DATABASE_URL"); dsn != "" {
		db, err = gorm.Open(postgres.Open(dsn), config)
	} else {
		db, err = gorm.Open(sqlite.Open(":memory:"), config)
		if err == nil { err = db.AutoMigrate(&{{.Resource.Name}}{}) }
	}
{{else}}	db, err = gorm.Open(sqlite.Open(":memory:"), config)
	if err == nil { err = db.AutoMigrate(&{{.Resource.Name}}{}) }
{{end}}	if err != nil { t.Fatal(err) }
	app := fiber.New()
	Register(app.Group("/api/v1"), db)
	basePath := "/api/v1{{.Resource.Route}}"
	escapeQuery := url.QueryEscape
	payload := map[string]any{
{{range .Resource.Fields}}		{{quote .Name}}: {{sampleGo .}},
{{end}}	}

	// Create.
	createdResponse := performJSON(t, app, http.MethodPost, basePath, payload)
	requireStatus(t, createdResponse, http.StatusCreated)
	var created struct { Data {{.Resource.Name}} ` + "`json:\"data\"`" + ` }
	if err := json.Unmarshal(createdResponse.Body.Bytes(), &created); err != nil { t.Fatal(err) }
	if created.Data.ID <= 0 || created.Data.CreatedAt.Location() != time.UTC || created.Data.UpdatedAt.Location() != time.UTC { t.Fatalf("invalid base fields: %#v", created.Data) }
{{if timeFields .Resource}}	var createdMap struct { Data map[string]any ` + "`json:\"data\"`" + ` }
	if err := json.Unmarshal(createdResponse.Body.Bytes(), &createdMap); err != nil { t.Fatal(err) }
{{range timeFields .Resource}}	if got := createdMap.Data[{{quote .Name}}]; got != "2026-01-02T03:04:05Z" { t.Fatalf("UTC {{.Name}} = %#v", got) }
{{end}}{{end}}

	// base field injection is rejected rather than mass-assigned.
	injected := map[string]any{"id": 999, "created_at": "2000-01-01T00:00:00Z"}
{{range .Resource.Fields}}	injected[{{quote .Name}}] = {{sampleGo .}}
{{end}}	requireStatus(t, performJSON(t, app, http.MethodPost, basePath, injected), http.StatusBadRequest)

{{with firstUnique .Resource}}	// A unique conflict maps to 409 without exposing the database error.
	conflict := performJSON(t, app, http.MethodPost, basePath, payload)
	requireStatus(t, conflict, http.StatusConflict)
	if strings.Contains(strings.ToLower(conflict.Body.String()), "unique constraint") { t.Fatal("unique conflict leaked database details") }
{{end}}
	// Get.
	detailPath := basePath + "/" + fmtID(created.Data.ID)
	requireStatus(t, performJSON(t, app, http.MethodGet, detailPath, nil), http.StatusOK)

	// List, pagination, and sort.
	list := performJSON(t, app, http.MethodGet, basePath+"?page=1&page_size=1&sort="+escapeQuery("-id"), nil)
	requireStatus(t, list, http.StatusOK)
	requireTotal(t, list, 1)
	if !bytes.Contains(list.Body.Bytes(), []byte(` + "`\"total_pages\":1`" + `)) { t.Fatalf("list envelope = %s", list.Body.String()) }
	requireStatus(t, performJSON(t, app, http.MethodGet, basePath+"?page_size=101", nil), http.StatusBadRequest)
	requireStatus(t, performJSON(t, app, http.MethodGet, basePath+"?page=9223372036854775807&page_size=100", nil), http.StatusBadRequest)
	requireStatus(t, performJSON(t, app, http.MethodGet, basePath+"?sort=not_allowed", nil), http.StatusBadRequest)
{{with firstSearch .Resource}}	search := performJSON(t, app, http.MethodGet, basePath+"?q="+escapeQuery({{quote (searchRaw .)}}), nil)
	requireStatus(t, search, http.StatusOK)
	requireTotal(t, search, 1)
{{end}}{{with firstFilter .Resource}}	filter := performJSON(t, app, http.MethodGet, basePath+"?{{.Name}}="+escapeQuery({{quote (filterRaw .)}}), nil)
	requireStatus(t, filter, http.StatusOK)
	requireTotal(t, filter, 1)
{{end}}{{with firstZero .Resource}}
	// A zero-value PATCH remains present (false, 0, or empty string).
	zeroPatch := performJSON(t, app, http.MethodPatch, detailPath, map[string]any{ {{quote .Name}}: {{zeroGo .}} })
	requireStatus(t, zeroPatch, http.StatusOK)
{{end}}{{with firstNullable .Resource}}
	// An explicit null is different from an omitted PATCH field.
	nullPatch := performJSON(t, app, http.MethodPatch, detailPath, map[string]any{ {{quote .Name}}: nil })
	requireStatus(t, nullPatch, http.StatusOK)
	var nullData struct { Data map[string]any ` + "`json:\"data\"`" + ` }
	if err := json.Unmarshal(nullPatch.Body.Bytes(), &nullData); err != nil { t.Fatal(err) }
	if value, exists := nullData.Data[{{quote .Name}}]; !exists || value != nil { t.Fatalf("explicit null was not persisted: %v", nullData.Data) }
{{end}}
	{{range timeFields .Resource}}{
		// Business time values are normalized to UTC on PATCH.
		timePatch := performJSON(t, app, http.MethodPatch, detailPath, map[string]any{ {{quote .Name}}: "2026-02-03T12:05:06+09:00" })
		requireStatus(t, timePatch, http.StatusOK)
		var timeData struct { Data map[string]any ` + "`json:\"data\"`" + ` }
		if err := json.Unmarshal(timePatch.Body.Bytes(), &timeData); err != nil { t.Fatal(err) }
		if got := timeData.Data[{{quote .Name}}]; got != "2026-02-03T03:05:06Z" { t.Fatalf("UTC PATCH {{.Name}} = %#v", got) }
	}
{{end}}
	// An empty update is rejected.
	requireStatus(t, performJSON(t, app, http.MethodPatch, detailPath, map[string]any{}), http.StatusBadRequest)
{{with firstRequired .Resource}}
	// Missing required input is a validation error.
	requireStatus(t, performJSON(t, app, http.MethodPost, basePath, map[string]any{}), http.StatusUnprocessableEntity)
{{end}}
	// Delete, then confirm 404.
	requireStatus(t, performJSON(t, app, http.MethodDelete, detailPath, nil), http.StatusNoContent)
	requireStatus(t, performJSON(t, app, http.MethodGet, detailPath, nil), http.StatusNotFound)
{{if hasDefaults .Resource}}
	// Database defaults are applied when optional fields are omitted.
	defaultPayload := map[string]any{
{{range .Resource.Fields}}{{if .Required}}		{{quote .Name}}: {{sampleGo .}},
{{end}}{{end}}	}
	defaultResponse := performJSON(t, app, http.MethodPost, basePath, defaultPayload)
	requireStatus(t, defaultResponse, http.StatusCreated)
	var defaultData struct { Data map[string]any ` + "`json:\"data\"`" + ` }
	if err := json.Unmarshal(defaultResponse.Body.Bytes(), &defaultData); err != nil { t.Fatal(err) }
	var expectedDefaults map[string]any
	if err := json.Unmarshal([]byte({{quote (defaultsJSON .Resource)}}), &expectedDefaults); err != nil { t.Fatal(err) }
	for name, want := range expectedDefaults {
		if got := defaultData.Data[name]; !reflect.DeepEqual(got, want) { t.Fatalf("default %s = %#v, want %#v", name, got, want) }
	}
	defaultID, ok := defaultData.Data["id"].(float64); if !ok { t.Fatalf("default id = %#v", defaultData.Data["id"]) }
	requireStatus(t, performJSON(t, app, http.MethodDelete, basePath+"/"+fmtID(int64(defaultID)), nil), http.StatusNoContent)
{{end}}
{{range defaultZeroFields .Resource}}	{
		// Explicit zero create values override database defaults.
		overridePayload := map[string]any{
{{range $.Resource.Fields}}{{if .Required}}			{{quote .Name}}: {{sampleGo .}},
{{end}}{{end}}			{{quote .Name}}: {{zeroGo .}},
		}
		overrideResponse := performJSON(t, app, http.MethodPost, basePath, overridePayload)
		requireStatus(t, overrideResponse, http.StatusCreated)
		var overrideData struct { Data map[string]any ` + "`json:\"data\"`" + ` }
		if err := json.Unmarshal(overrideResponse.Body.Bytes(), &overrideData); err != nil { t.Fatal(err) }
		var want any; if err := json.Unmarshal([]byte({{quote (zeroExpectedJSON .)}}), &want); err != nil { t.Fatal(err) }
		if got := overrideData.Data[{{quote .Name}}]; !reflect.DeepEqual(got, want) { t.Fatalf("explicit zero {{.Name}} = %#v, want %#v", got, want) }
		overrideID := int64(overrideData.Data["id"].(float64))
		requireStatus(t, performJSON(t, app, http.MethodDelete, basePath+"/"+fmtID(overrideID), nil), http.StatusNoContent)
	}
{{end}}{{range nullableDefaultFields .Resource}}	{
		// Explicit null create values override non-null database defaults.
		nullDefaultPayload := map[string]any{
{{range $.Resource.Fields}}{{if .Required}}			{{quote .Name}}: {{sampleGo .}},
{{end}}{{end}}			{{quote .Name}}: nil,
		}
		nullDefaultResponse := performJSON(t, app, http.MethodPost, basePath, nullDefaultPayload)
		requireStatus(t, nullDefaultResponse, http.StatusCreated)
		var nullDefaultData struct { Data map[string]any ` + "`json:\"data\"`" + ` }
		if err := json.Unmarshal(nullDefaultResponse.Body.Bytes(), &nullDefaultData); err != nil { t.Fatal(err) }
		if got := nullDefaultData.Data[{{quote .Name}}]; got != nil { t.Fatalf("explicit null {{.Name}} = %#v", got) }
		secondNullResponse := performJSON(t, app, http.MethodPost, basePath, nullDefaultPayload)
		requireStatus(t, secondNullResponse, http.StatusCreated)
		var secondNullData struct { Data map[string]any ` + "`json:\"data\"`" + ` }
		if err := json.Unmarshal(secondNullResponse.Body.Bytes(), &secondNullData); err != nil { t.Fatal(err) }
		if got := secondNullData.Data[{{quote .Name}}]; got != nil { t.Fatalf("second explicit null {{.Name}} = %#v", got) }
		nullDefaultID := int64(nullDefaultData.Data["id"].(float64))
		secondNullID := int64(secondNullData.Data["id"].(float64))
		requireStatus(t, performJSON(t, app, http.MethodDelete, basePath+"/"+fmtID(nullDefaultID), nil), http.StatusNoContent)
		requireStatus(t, performJSON(t, app, http.MethodDelete, basePath+"/"+fmtID(secondNullID), nil), http.StatusNoContent)
	}
{{end}}
{{if optionalJSONFields .Resource}}	{
		// Omitted optional, non-null JSON fields use an empty object instead of SQL NULL.
		jsonPayload := map[string]any{
{{range .Resource.Fields}}{{if .Required}}			{{quote .Name}}: {{sampleGo .}},
{{end}}{{end}}		}
		jsonResponse := performJSON(t, app, http.MethodPost, basePath, jsonPayload)
		requireStatus(t, jsonResponse, http.StatusCreated)
		var jsonData struct { Data map[string]any ` + "`json:\"data\"`" + ` }
		if err := json.Unmarshal(jsonResponse.Body.Bytes(), &jsonData); err != nil { t.Fatal(err) }
{{range optionalJSONFields .Resource}}		if value, ok := jsonData.Data[{{quote .Name}}].(map[string]any); !ok || len(value) != 0 { t.Fatalf("omitted JSON {{.Name}} = %#v", jsonData.Data[{{quote .Name}}]) }
{{end}}		jsonID := int64(jsonData.Data["id"].(float64))
		requireStatus(t, performJSON(t, app, http.MethodDelete, basePath+"/"+fmtID(jsonID), nil), http.StatusNoContent)
	}
{{end}}

	// internal error redaction never exposes SQL, the SQLite DSN, or paths.
	sqlDB, err := db.DB(); if err != nil { t.Fatal(err) }
	if err := sqlDB.Close(); err != nil { t.Fatal(err) }
	internal := performJSON(t, app, http.MethodGet, basePath, nil)
	requireStatus(t, internal, http.StatusInternalServerError)
	lowerBody := strings.ToLower(internal.Body.String())
	for _, secret := range []string{"select ", "sqlite", ":memory:", "/internal/"} {
		if strings.Contains(lowerBody, secret) { t.Fatalf("internal error leaked %q: %s", secret, internal.Body.String()) }
	}
}

func performJSON(t *testing.T, app *fiber.App, method, path string, payload any) *httptest.ResponseRecorder {
	t.Helper()
	var body *bytes.Reader
	if payload == nil { body = bytes.NewReader(nil) } else { data, err := json.Marshal(payload); if err != nil { t.Fatal(err) }; body = bytes.NewReader(data) }
	request := httptest.NewRequest(method, path, body)
	request.Header.Set("Content-Type", "application/json")
	response, err := app.Test(request, fiber.TestConfig{Timeout: 30 * time.Second})
	if err != nil { t.Fatal(err) }
	defer response.Body.Close()
	recorder := httptest.NewRecorder()
	recorder.Code = response.StatusCode
	payloadBody, err := io.ReadAll(response.Body)
	if err != nil { t.Fatal(err) }
	if _, err := recorder.Body.Write(payloadBody); err != nil { t.Fatal(err) }
	for key, values := range response.Header {
		for _, value := range values {
			recorder.Header().Add(key, value)
		}
	}
	return recorder
}

func requireStatus(t *testing.T, response *httptest.ResponseRecorder, want int) {
	t.Helper()
	if response.Code != want { t.Fatalf("status = %d, want %d, body = %s", response.Code, want, response.Body.String()) }
}

func requireTotal(t *testing.T, response *httptest.ResponseRecorder, want int64) {
	t.Helper()
	var envelope struct { Data struct { Total int64 ` + "`json:\"total\"`" + ` } ` + "`json:\"data\"`" + ` }
	if err := json.Unmarshal(response.Body.Bytes(), &envelope); err != nil { t.Fatal(err) }
	if envelope.Data.Total != want { t.Fatalf("total = %d, want %d, body = %s", envelope.Data.Total, want, response.Body.String()) }
}

func fmtID(id int64) string { return strconv.FormatInt(id, 10) }
`

const registerTemplateFiber = `// Code generated by gobackend; DO NOT EDIT.

package generated

import (
	"github.com/gofiber/fiber/v3"
	"gorm.io/gorm"
{{range .Resources}}	{{if ne (resourceImportName .) .Package}}{{resourceImportName .}} {{end}}"{{$.Module}}/internal/resources/{{.Package}}"
{{end}})

func Register(router fiber.Router, db *gorm.DB) {
{{range .Resources}}	{{resourceImportName .}}.Register(router, db)
{{end}}}
`
